config/routes.rb
Rails.application.routes.draw do
  resources :transactions

   root 'transactions#index'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    @transaction.pre_tip_cost = @transaction.pre_tip_cost*100
    @transaction.post_tip = (@transaction.pre_tip_cost * (@transaction.tip_percentage+100))/100
    @transaction.individual_contribution = @transaction.post_tip / (@transaction.number_splitting + 1)

    # Adjusts Amount - Divides by 100. Amount saved as integer, not decimal. Negative# =Charge, Positive# =Payment
    @individual_contribution_adjusted = -(@transaction.individual_contribution / 100)
    #Converts note to url appropriate note for API request
    @note_adjusted = convert_string_to_url(@transaction.note)
    # NO OAuth currently - my access token used.    
    @access_token = 'grR2SCEm2C7HdWGukWQEJyW6RpEWJYp3'    
    
    # Static POST request sent via Venmo's API, NO OAuth.
    response = HTTParty.post("https://api.venmo.com/v1/payments?access_token=#{@access_token}&phone=#{@transaction.phone_number_charged}&amount=#{@individual_contribution_adjusted}&note=#{@note_adjusted}&audience=#{@transaction.audience}")
    puts response.body, response.code, response.message, response.headers.inspect


  # POST /transactions
  # POST
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def convert_string_to_url(string)
    string.gsub(" ", "%20")
    string.gsub("?", "%3F")
    string.gsub("$", "%24")
    string.gsub("@", "%40")
    string.gsub("#", "%23")
    string.gsub("&", "%26")
    string.gsub("+", "%2B")
    string.gsub("=", "%3D")
    string.gsub("^", "%5E")
    string.gsub("/", "%2F")
    string.gsub(":", "%3A")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:pre_tip_cost, :note, :number_splitting, :tip_percentage, :post_tip, :audience, :phone_number_charged)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SplitCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  My bill for 
    <%= f.text_field :note %>
  is 
      $<%= f.number_field :pre_tip_cost %>. 
  </br>
  I'd like to give a
    <%= f.select(:tip_percentage, [15, 20, 25], {}) %> % tip, and
  I'll be splitting it with 
    <%= f.number_field :number_splitting %>
  other people.
  </br>

  The friend I'd like to charge can be found through zer phone number: <%= f.text_field :phone_number_charged %>.
  </br>
  Please keep this transaction <%= f.select(:audience, ["private", "public"]) %>.

  <div class="actions">
    <%= f.submit "Charge my friends!"%>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Pre tip cost</th>
      <th>Number of Friends</th>
      <th>Tip percentage</th>
      <th>Post tip</th>
      <th>Friends Owe: </th>
      <th colspan="3"></th>
      <th>Phone#OfFriendCharged:</th>
<!--       <th>Access Token:</th> -->
      <th>Audience:</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <!-- TODO: cannot merely divide by 100, must instead edit view of raw ruby number to display decimal $ amounts. -->
        <td><%= transaction.note %></td>
        <td>$<%= transaction.pre_tip_cost / 100 %></td>
        <td><%= transaction.number_splitting %> people</td>
        <td><%= transaction.tip_percentage %>%</td>
        <td>$<%= transaction.post_tip / 100 %></td>
        <td>$<%= transaction.individual_contribution / 100 %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>--- <%= transaction.phone_number_charged %></td>
<!--         <td>---blahblah <%#= transaction.%></td>       -->
        <td>--- <%= transaction.audience %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h2>The waiter arrives, smiling, and hands your table the check. That's right--you and your 7 friends are given just one check.</h2>
<h3> Therefore, we've made this app to help you calculate the total after your tip and to charge friends through Venmo for their contribution.
</h3>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>


Hi friends! The "<%= @transaction.note %>" was <%= (@transaction.post_tip/100) %> after a <%= @transaction.tip_percentage %>% tip. 
</br>
</br>
Each friend will need to pay $<%= (@transaction.individual_contribution/100) %>.


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/welcome/index.html.erb
<h1> Venmo SplitCheck API Play </h1>

<h2>Please Input the Total Amount you are paying for this meal: </h2>


<h2></h2>